version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./data:/data
    command: >
      sh -c "python main.py"
    networks:
      - net_db
    depends_on:
      - db

  bot:
    build:
      context: .
    volumes:
      - ./bot:/bot
    command: >
      sh -c "python ../bot/main.py"
    networks:
      - net_db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=bot_data
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${DB_PORT}:5432
    networks:
      - net_db

networks:
  net_db:
