version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./data:/data
    command: >
      sh -c "python main.py"
    networks:
      - net_db
    depends_on:
      - db
  
  bot:
    build:
      context: .
    volumes:
      - ./bot:/bot
    command: >
      sh -c "python ../bot/main.py"
    networks:
      - net_db
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    networks:
      - net_db

networks:
  net_db: