version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    command: >
      sh -c "python main.py"
  
  bot:
    build:
      context: .
    volumes:
      - ./bot:/bot
    command: >
      sh -c "python ../bot/start.py"