---
name: Checks

on: [push, pull_request_review]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Data
        run: docker-compose run --rm app sh -c "pytest"

      - name: Lint Data
        run: docker-compose run --rm app sh -c "flake8"
      
      - name: Test Bot
        run: docker-compose run --rm bot sh -c "pytest"

      - name: Lint Bot
        run: docker-compose run --rm bot sh -c "flake8"