name: Deploy Bot Beta

on:
  push:
    branches:
      - "deploy/**"

jobs:
  deploy-bot-beta:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DC_HOST }}
          username: ${{ secrets.DC_USER }}
          key: ${{ secrets.DC_KEY }}
          script: ${{ secrets.SCRIPT_DP }}
